openapi: 3.0.1
info:
  title: aion-backend
  version: 0.1.0
servers:
- url: "{server}:{port}/employee"
  variables:
    server:
      default: http://localhost
    port:
      default: "8080"
paths:
  /all:
    get:
      operationId: getAllEmployees
      responses:
        "200":
          description: Ok
          content:
            application/json:
